In [36]:
import os
from dotenv import load_dotenv
from neo4j import GraphDatabase
from pathlib import Path

In [37]:
env_path = Path("/home/luis/Documents/FGV/Laboratory/document-graph/server/.env")

load_dotenv(dotenv_path=env_path)

neo4j_uri = os.getenv("NEO4J_URI", "bolt://localhost:7687")
neo4j_username = os.getenv("NEO4J_USERNAME", "neo4j")
neo4j_password = os.getenv("NEO4J_PASSWORD", "neo4j_password")
neo4j_database = os.getenv("NEO4J_DATABASE", "neo4j")

In [38]:
driver = GraphDatabase.driver(
    neo4j_uri,
    auth=(neo4j_username, neo4j_password),
)

def run_query(query: str, params: dict | None = None):
    with driver.session(database=neo4j_database) as session:
        result = session.run(query, params or {})
        return [r.data() for r in result]

In [39]:
# 1) Ver contratos cargados
run_query("""
MATCH (c:Contract)
RETURN c.path AS path, c.content_hash AS content_hash
ORDER BY path
""")

[{'path': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1-Supply Agreement.json',
  'content_hash': '4a2187cb60da96c331433608de54893734fbde45'},
 {'path': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/BLUEFLYINC_03_27_2002-EX-10.27-e-business Hosting Agreement.json',
  'content_hash': 'cd18362093e0c4ba3cbcb68912fd0ef5459d35bf'},
 {'path': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/HealthcentralCom_19991108_S-1A_EX-10.27_6623292_EX-10.27_Co-Branding Agreement.json',
  'content_hash': '7fd9202dec18af0ff98136de4ba2c2998f4c1a13'},
 {'path': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_Affiliate Agreement.json',
  'content_hash': 'f3245eb60b42b2e3c7f79eb0f075801474bdcb46'}]

In [40]:
# 2) Conteo por tipo de nodo
run_query("""
MATCH (n:KGNode)
RETURN n.node_type AS node_type, count(*) AS total
ORDER BY total DESC
""")

[{'node_type': 'Clause', 'total': 921},
 {'node_type': 'Obligation', 'total': 84},
 {'node_type': 'DefinedTerm', 'total': 38},
 {'node_type': 'Right', 'total': 26},
 {'node_type': 'Prohibition', 'total': 16},
 {'node_type': 'Party', 'total': 10},
 {'node_type': 'Condition', 'total': 9},
 {'node_type': 'Reference', 'total': 2},
 {'node_type': 'Value', 'total': 2}]

In [41]:
# 3) Conteo por tipo de relación
run_query("""
MATCH (:KGNode)-[r]->(:KGNode)
RETURN type(r) AS rel_type, count(*) AS total
ORDER BY total DESC
""")

[{'rel_type': 'REFERENCES', 'total': 659},
 {'rel_type': 'CONTAINS', 'total': 239},
 {'rel_type': 'IS_PART_OF', 'total': 233},
 {'rel_type': 'ASSIGNS_OBLIGATION_TO', 'total': 70},
 {'rel_type': 'GRANTS_RIGHT_TO', 'total': 30},
 {'rel_type': 'DEFINES', 'total': 10},
 {'rel_type': 'DEPENDS_ON', 'total': 9},
 {'rel_type': 'USES', 'total': 6}]

In [42]:
run_query("""
MATCH (ct:Contract)
OPTIONAL MATCH (ct)-[:CONTAINS]->(n:KGNode)
WITH ct, count(DISTINCT n) AS nodes
OPTIONAL MATCH (ct)-[:CONTAINS]->(a:KGNode)-[r]-(:KGNode)<-[:CONTAINS]-(ct)
RETURN
  ct.path AS contract,
  nodes,
  count(DISTINCT id(r)) AS edges
ORDER BY contract
""")

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=9, column=18, offset=233>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 233, 'line': 9, 'column': 18}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\nMATCH (ct:Contract)\nOPTIONAL MATCH (ct)-[:CONTAINS]->(n:KGNode)\nWITH ct, count(DISTINCT n) AS nodes\nOPTIONAL MATCH (ct)-[:CONTAINS]->(a:KGNode)-[r]-(:KGNode)<-[:CONTAINS]-(ct)\nRETURN\n  ct.path AS contract,\n  nodes,\n  count(DISTINCT id(r)) AS edges\nORDER BY contract\n'

[{'contract': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1-Supply Agreement.json',
  'nodes': 490,
  'edges': 775},
 {'contract': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/BLUEFLYINC_03_27_2002-EX-10.27-e-business Hosting Agreement.json',
  'nodes': 265,
  'edges': 233},
 {'contract': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/HealthcentralCom_19991108_S-1A_EX-10.27_6623292_EX-10.27_Co-Branding Agreement.json',
  'nodes': 238,
  'edges': 97},
 {'contract': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_Affiliate Agreement.json',
  'nodes': 115,
  'edges': 151}]

In [43]:
run_query("""
MATCH (ct:Contract)
OPTIONAL MATCH (ct)-[:CONTAINS]->(n:KGNode)
WITH ct, collect(DISTINCT n) AS nodes
UNWIND nodes AS n
OPTIONAL MATCH (ct)-[:CONTAINS]->(n)-[r]-(:KGNode)<-[:CONTAINS]-(ct)
WITH ct.path AS contract, n, count(DISTINCT id(r)) AS deg
WITH
  contract,
  count(n) AS total_nodes,
  sum(CASE WHEN deg > 0 THEN 1 ELSE 0 END) AS connected_nodes,
  sum(CASE WHEN deg = 0 THEN 1 ELSE 0 END) AS isolated_nodes,
  round(avg(deg), 3) AS avg_degree
RETURN
  contract,
  total_nodes,
  connected_nodes,
  isolated_nodes,
  round(100.0 * isolated_nodes / total_nodes, 2) AS isolated_pct,
  avg_degree
ORDER BY isolated_pct DESC, contract
""")

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=7, column=45, offset=234>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 234, 'line': 7, 'column': 45}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\nMATCH (ct:Contract)\nOPTIONAL MATCH (ct)-[:CONTAINS]->(n:KGNode)\nWITH ct, collect(DISTINCT n) AS nodes\nUNWIND nodes AS n\nOPTIONAL MATCH (ct)-[:CONTAINS]->(n)-[r]-(:KGNode)<-[:CONTAINS]-(ct)\nWITH ct.path AS contract, n, count(DISTINCT id(r)) AS deg\nWITH\n  contract,\n  count(n) AS total_nodes,\n  sum(CASE WHEN deg > 0 THEN 1 ELSE 0 END) AS connected_nodes,\n  sum(CASE WHEN deg = 0 THEN 1 ELSE 0 END) AS isolated_nodes,\n  round(avg(deg), 3) AS avg_degree\nRETURN\n  contract,\n  total_nodes,\n  connected_nodes,\n  isolated_nodes,\n  round(100.0 * isolated_nodes / total_nodes, 2) AS isolated_pct,\n  avg_degree\nORDER BY isolated_pct DESC, contract\n'

[{'contract': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/HealthcentralCom_19991108_S-1A_EX-10.27_6623292_EX-10.27_Co-Branding Agreement.json',
  'total_nodes': 238,
  'connected_nodes': 65,
  'isolated_nodes': 173,
  'isolated_pct': 72.69,
  'avg_degree': 0.815},
 {'contract': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/BLUEFLYINC_03_27_2002-EX-10.27-e-business Hosting Agreement.json',
  'total_nodes': 265,
  'connected_nodes': 152,
  'isolated_nodes': 113,
  'isolated_pct': 42.64,
  'avg_degree': 1.758},
 {'contract': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_Affiliate Agreement.json',
  'total_nodes': 115,
  'connected_nodes': 75,
  'isolated_nodes': 40,
  'isolated_pct': 34.78,
  'avg_degree': 2.626},
 {'contract': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1-Supply Agreement.json',
  'total_nodes': 490,
  'connected_nodes': 392,
  'isolated_nodes': 98,
  'isolated_pct': 20.0,
  'avg_degree': 3.163}]

In [44]:
run_query("""
MATCH (ct:Contract)-[:CONTAINS]->(n:KGNode)
OPTIONAL MATCH (ct)-[:CONTAINS]->(n)-[r]-(:KGNode)<-[:CONTAINS]-(ct)
WITH ct.path AS contract, n, count(DISTINCT id(r)) AS deg
WHERE deg = 0
RETURN
  contract,
  n.node_type AS isolated_node_type,
  count(*) AS total
ORDER BY contract, total DESC
""")

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=45, offset=158>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 158, 'line': 4, 'column': 45}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\nMATCH (ct:Contract)-[:CONTAINS]->(n:KGNode)\nOPTIONAL MATCH (ct)-[:CONTAINS]->(n)-[r]-(:KGNode)<-[:CONTAINS]-(ct)\nWITH ct.path AS contract, n, count(DISTINCT id(r)) AS deg\nWHERE deg = 0\nRETURN\n  contract,\n  n.node_type AS isolated_node_type,\n  count(*) AS total\nORDER BY contract, total DESC\n'

[{'contract': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1-Supply Agreement.json',
  'isolated_node_type': 'Clause',
  'total': 98},
 {'contract': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/BLUEFLYINC_03_27_2002-EX-10.27-e-business Hosting Agreement.json',
  'isolated_node_type': 'Clause',
  'total': 113},
 {'contract': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/HealthcentralCom_19991108_S-1A_EX-10.27_6623292_EX-10.27_Co-Branding Agreement.json',
  'isolated_node_type': 'Clause',
  'total': 173},
 {'contract': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_Affiliate Agreement.json',
  'isolated_node_type': 'Clause',
  'total': 40}]

In [45]:
# run_query("""
# MATCH (ct:Contract)-[:CONTAINS]->(c:Clause)
# MATCH (ct)-[:CONTAINS]->(c)-[r]-(m:KGNode)<-[:CONTAINS]-(ct)
# RETURN
#   ct.path AS contract,
#   c.node_id AS clause_id,
#   m.node_type AS neighbor_type,
#   count(DISTINCT id(r)) AS rel_count
# ORDER BY contract, clause_id, rel_count DESC
# """)

In [46]:
run_query("""
MATCH (ct:Contract)-[:CONTAINS]->(c:Clause {paragraph_uid: $paragraph_uid})
OPTIONAL MATCH (ct)-[:CONTAINS]->(c)-[r]-(m:KGNode)<-[:CONTAINS]-(ct)
WITH ct, c,
     collect(DISTINCT CASE
       WHEN r IS NULL THEN NULL
       ELSE {
         relation: type(r),
         direction: CASE WHEN startNode(r)=c THEN "OUT" ELSE "IN" END,
         node_id: m.node_id,
         node_type: m.node_type,
         label: m.label
       }
     END) AS raw_neighbors
WITH ct, c, [x IN raw_neighbors WHERE x IS NOT NULL] AS neighbors
RETURN
  ct.path AS contract,
  c.node_id AS clause_node_id,
  c.source_paragraph_id AS source_paragraph_id,
  c.paragraph_uid AS paragraph_uid,
  size(neighbors) = 0 AS is_isolated,
  neighbors
ORDER BY contract;
""", params={"paragraph_uid": "1152e6cb7388c71fdafe8f45698bd0200f7e438e"})

[{'contract': '/home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1-Supply Agreement.json',
  'clause_node_id': '4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-10',
  'source_paragraph_id': 'BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1-Supply Agreement-p-10',
  'paragraph_uid': '1152e6cb7388c71fdafe8f45698bd0200f7e438e',
  'is_isolated': False,
  'neighbors': [{'node_type': 'Party',
    'label': 'Miltenyi Biotec GmbH',
    'relation': 'CONTAINS',
    'node_id': '4a2187cb60da96c331433608de54893734fbde45:Party:bcdc9ac6edf65122',
    'direction': 'OUT'},
   {'node_type': 'Party',
    'label': 'Bellicum Pharmaceuticals, Inc',
    'relation': 'CONTAINS',
    'node_id': '4a2187cb60da96c331433608de54893734fbde45:Party:4e08f283873a4ed2',
    'direction': 'OUT'},
   {'node_type': 'Party',
    'label': 'Miltenyi Biotec GmbH',
    'relation': 'IS_PART_OF',
    'node_id': '4a2187cb60da96c331433608de54893734fbde45:Party:bcdc9ac6edf65122',
    'direction': 'IN'},
   {'node_type': 'Party',
    'label': 'Bellicum Pharmaceuticals, Inc',
    'relation': 'IS_PART_OF',
    'node_id': '4a2187cb60da96c331433608de54893734fbde45:Party:4e08f283873a4ed2',
    'direction': 'IN'}]}]

In [47]:
document_list = [
    "BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1-Supply Agreement",
    "BLUEFLYINC_03_27_2002-EX-10.27-e-business Hosting Agreement",
    "HealthcentralCom_19991108_S-1A_EX-10.27_6623292_EX-10.27_Co-Branding Agreement",
    "LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_Affiliate Agreement",
]

In [48]:
import json

MAX = 5

docs = {}
for js in document_list:
    relationsCounts = []
    # with open(f"../../infra/json/graph/{js}.json", "r") as f:
    #     data = json.load(f)
    with open(f"../../infra/json/graph/{js}.json", "r") as f:
        data = json.load(f)

    nodes = data.get("nodes", [])
    edges = data.get("edges", [])

    for node in nodes:
        node_id = node.get("id")
        paragraph_uid = node.get("paragraph_uid")
        relationsCount = node.get("relationsCount", 0)
        relationsCounts.append((node_id, relationsCount))
    
    relationsCounts.sort(key=lambda x: x[1], reverse=True)
    top_relations = relationsCounts[:MAX]
    
    docs[js] = top_relations

In [49]:
def analyze_clause_neighbors(paragraph_uid: str):
    return run_query("""
    MATCH (ct:Contract)-[:CONTAINS]->(c:Clause {paragraph_uid: $paragraph_uid})
    OPTIONAL MATCH (ct)-[:CONTAINS]->(c)-[r]-(m:KGNode)<-[:CONTAINS]-(ct)
    WITH ct, c,
        collect(DISTINCT CASE
        WHEN r IS NULL THEN NULL
        ELSE {
            relation: type(r),
            direction: CASE WHEN startNode(r)=c THEN "OUT" ELSE "IN" END,
            node_id: m.node_id,
            node_type: m.node_type,
            label: m.label
        }
        END) AS raw_neighbors
    WITH ct, c, [x IN raw_neighbors WHERE x IS NOT NULL] AS neighbors
    RETURN
    ct.path AS contract,
    c.node_id AS clause_node_id,
    c.source_paragraph_id AS source_paragraph_id,
    c.paragraph_uid AS paragraph_uid,
    size(neighbors) = 0 AS is_isolated,
    neighbors
    ORDER BY contract;
    """, params={"paragraph_uid": f"{paragraph_uid}"})

In [50]:
# for key, value in docs.items():
#     for node_id, relationsCount in value:
#         print(f"Document: {key}, Node ID: {node_id}, Relations Count: {relationsCount}")
#         neighbors_info = analyze_clause_neighbors(node_id)
#         print(json.dumps(neighbors_info, indent=2))

In [51]:
import json
import pandas as pd
from pathlib import Path

q = """
MATCH (ct:Contract)-[:CONTAINS]->(c:Clause)
OPTIONAL MATCH (ct)-[:CONTAINS]->(c)-[r]-(:KGNode)<-[:CONTAINS]-(ct)
WITH ct.path AS contract, c, count(DISTINCT id(r)) AS kg_degree
WHERE kg_degree > 0
RETURN
  contract,
  c.node_id AS clause_node_id,
  c.source_paragraph_id AS source_paragraph_id,
  c.paragraph_uid AS paragraph_uid,
  kg_degree
"""

def get_relcount(contract_path: str, source_paragraph_id: str) -> int:
    if contract_path not in rel_:
        p = Path(contract_path)
        payload = json.loads(p.read_text(encoding="utf-8"))
        if isinstance(payload.get("graph"), dict):
            payload = payload["graph"]
        rel_map = {}
        for n in payload.get("nodes", []):
            nid = str(n.get("id", "")).strip()
            if nid:
                rel_map[nid] = int(n.get("relationsCount", 0) or 0)
        rel_[contract_path] = rel_map
    return rel_[contract_path].get(str(source_paragraph_id), 0)

kg_df = pd.DataFrame(run_query(q))

if kg_df.empty:
    print("No hay cláusulas no aisladas en KG.")
else:
    rel_ = {}
    kg_df["base_relationsCount"] = kg_df.apply(
        lambda x: get_relcount(x["contract"], x["source_paragraph_id"]), axis=1
    )

    top5 = (
        kg_df.sort_values(
            by=["contract", "base_relationsCount", "kg_degree"],
            ascending=[True, False, False],
        )
        .groupby("contract", as_index=False)
        .head(5)
        .reset_index(drop=True)
    )

    display(
        top5[
            ["contract", "source_paragraph_id", "paragraph_uid", "base_relationsCount", "kg_degree"]
        ]
    )

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=45, offset=158>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 158, 'line': 4, 'column': 45}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\nMATCH (ct:Contract)-[:CONTAINS]->(c:Clause)\nOPTIONAL MATCH (ct)-[:CONTAINS]->(c)-[r]-(:KGNode)<-[:CONTAINS]-(ct)\nWITH ct.path AS contract, c, count(DISTINCT id(r)) AS kg_degree\nWHERE kg_degree > 0\nRETURN\n  contract,\n  c.node_id AS clause_node_id,\n  c.source_paragraph_id AS source_paragraph_id,\n  c.paragraph_uid AS paragraph_uid,\n  kg_degree\n'

,contract,source_paragraph_id,paragraph_uid,base_relationsCount,kg_degree
0,/home/luis/Documents/FGV/Laboratory/document-g...,"BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1...",6d843a956f1adcbf7394d27457e8342f020a9ed8,121,121
1,/home/luis/Documents/FGV/Laboratory/document-g...,"BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1...",c3dcf35efbbd129ee4e08d34cb26109be2dc9737,36,31
2,/home/luis/Documents/FGV/Laboratory/document-g...,"BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1...",102fafa0ede1ad48835bc9d844bf234a120a5986,35,31
3,/home/luis/Documents/FGV/Laboratory/document-g...,"BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1...",27aa2a37e94374ded441a3fc6491ab467ffa30d1,34,31
4,/home/luis/Documents/FGV/Laboratory/document-g...,"BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1...",c0ca305f958217b50991bc9690c0c2e5abb4a281,27,27
5,/home/luis/Documents/FGV/Laboratory/document-g...,BLUEFLYINC_03_27_2002-EX-10.27-e-business Host...,5b869cb5dd4181e2d1fa9369658bade12df646aa,23,23
6,/home/luis/Documents/FGV/Laboratory/document-g...,BLUEFLYINC_03_27_2002-EX-10.27-e-business Host...,73d6b2e02e341ef55b895737ad0340470d984fb0,8,8
7,/home/luis/Documents/FGV/Laboratory/document-g...,BLUEFLYINC_03_27_2002-EX-10.27-e-business Host...,c222917d975e61e910f6bd65ca4d075e445d9692,8,8
8,/home/luis/Documents/FGV/Laboratory/document-g...,BLUEFLYINC_03_27_2002-EX-10.27-e-business Host...,e0633e8c9bba5eb0a6944c50bb5eb38b71b7b184,6,6
9,/home/luis/Documents/FGV/Laboratory/document-g...,BLUEFLYINC_03_27_2002-EX-10.27-e-business Host...,e66ef6eee17776881f3fa30b0de56fd46c847b2b,6,5
10,/home/luis/Documents/FGV/Laboratory/document-g...,HealthcentralCom_19991108_S-1A_EX-10.27_662329...,151d55f9ea0045b49cca9fc0f0e4a0be45e35ad2,2,4
11,/home/luis/Documents/FGV/Laboratory/document-g...,HealthcentralCom_19991108_S-1A_EX-10.27_662329...,1bd9d869d7aee8927bac521eed027ba74c2424dc,1,2
12,/home/luis/Documents/FGV/Laboratory/document-g...,HealthcentralCom_19991108_S-1A_EX-10.27_662329...,728175baca99a419d9f87ca75760f8e7cf144856,1,2
13,/home/luis/Documents/FGV/Laboratory/document-g...,HealthcentralCom_19991108_S-1A_EX-10.27_662329...,e68bc9c1c2ebb65f2dee54c03093d6a0ddaec730,1,2
14,/home/luis/Documents/FGV/Laboratory/document-g...,HealthcentralCom_19991108_S-1A_EX-10.27_662329...,43004e17d4ee7c6073f0b7a4472b404e50d82278,1,2
15,/home/luis/Documents/FGV/Laboratory/document-g...,LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_...,0a3ca0c7211beb712106f2eb83b4e41507ff9c8f,38,38
16,/home/luis/Documents/FGV/Laboratory/document-g...,LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_...,45736548f7e35504b24a48ad8481cd10d885e32f,13,15
17,/home/luis/Documents/FGV/Laboratory/document-g...,LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_...,6fbb673ff89b902981940c32cee1436b71c894b8,13,13
18,/home/luis/Documents/FGV/Laboratory/document-g...,LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_...,f9047369067aecb510cddc383d51d4435169f8ec,5,5
19,/home/luis/Documents/FGV/Laboratory/document-g...,LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_...,c34875a8f5856d01b3b1f9e3a93f0cfdb57d8e04,5,3

In [52]:
# driver.close()

In [53]:
import json
import pandas as pd
from pathlib import Path


def select_top_k_non_isolated(document_list: list[str], top_k: int = 5) -> pd.DataFrame:
    q = """
    MATCH (ct:Contract)-[:CONTAINS]->(c:Clause)
    OPTIONAL MATCH (ct)-[:CONTAINS]->(c)-[r]-(:KGNode)<-[:CONTAINS]-(ct)
    WITH ct.path AS contract, c, count(DISTINCT id(r)) AS kg_degree
    WHERE kg_degree > 0
      AND ANY(doc IN $document_list WHERE contract CONTAINS doc)
    RETURN
      contract,
      c.node_id AS clause_node_id,
      c.source_paragraph_id AS source_paragraph_id,
      c.paragraph_uid AS paragraph_uid,
      kg_degree
    """

    kg_df = pd.DataFrame(run_query(q, params={"document_list": document_list}))
    if kg_df.empty:
        return kg_df

    rel_cache: dict[str, dict[str, int]] = {}

    def get_relcount(contract_path: str, source_paragraph_id: str) -> int:
        if contract_path not in rel_cache:
            payload = json.loads(Path(contract_path).read_text(encoding="utf-8"))
            if isinstance(payload.get("graph"), dict):
                payload = payload["graph"]
            rel_map = {}
            for n in payload.get("nodes", []):
                nid = str(n.get("id", "")).strip()
                if nid:
                    rel_map[nid] = int(n.get("relationsCount", 0) or 0)
            rel_cache[contract_path] = rel_map
        return rel_cache[contract_path].get(str(source_paragraph_id), 0)

    kg_df["base_relationsCount"] = kg_df.apply(
        lambda x: get_relcount(x["contract"], x["source_paragraph_id"]), axis=1
    )

    topk = (
        kg_df.sort_values(
            by=["contract", "base_relationsCount", "kg_degree"],
            ascending=[True, False, False],
        )
        .groupby("contract", as_index=False)
        .head(top_k)
        .reset_index(drop=True)
    )
    return topk


def _fetch_seed_clause(paragraph_uid: str) -> dict:
    q = """
    MATCH (ct:Contract)-[:CONTAINS]->(c:Clause {paragraph_uid: $paragraph_uid})
    RETURN
      ct.path AS contract,
      c.node_id AS clause_node_id,
      c.source_paragraph_id AS source_paragraph_id,
      c.paragraph_uid AS paragraph_uid,
      coalesce(c.text, "") AS clause_text
    LIMIT 1
    """
    rows = run_query(q, params={"paragraph_uid": paragraph_uid})
    return rows[0] if rows else {}


def _fetch_hop_edges(paragraph_uid: str, hops: int) -> list[dict]:
    if hops not in (1, 2):
        raise ValueError("hops must be 1 or 2")

    q = f"""
    MATCH (ct:Contract)-[:CONTAINS]->(c:Clause {{paragraph_uid: $paragraph_uid}})
    MATCH p=(c)-[*1..{hops}]-(n:KGNode)
    WHERE ALL(x IN nodes(p)[1..] WHERE (ct)-[:CONTAINS]->(x))
    UNWIND relationships(p) AS rel
    WITH DISTINCT ct, rel, startNode(rel) AS s, endNode(rel) AS t
    RETURN
      ct.path AS contract,
      s.node_id AS source_id,
      s.node_type AS source_type,
      s.label AS source_label,
      properties(s) AS source_props,
      type(rel) AS rel_type,
      properties(rel) AS rel_props,
      t.node_id AS target_id,
      t.node_type AS target_type,
      t.label AS target_label,
      properties(t) AS target_props
    ORDER BY rel_type, source_id, target_id
    """
    return run_query(q, params={"paragraph_uid": paragraph_uid})


def _node_snippet(node_type: str, props: dict) -> str:
    keys = ["text", "term", "name", "action", "trigger", "amount", "definition", "citation"]
    text = ""
    for k in keys:
        val = props.get(k)
        if isinstance(val, str) and val.strip():
            text = val.strip()
            break
    if not text:
        text = props.get("id_raw", "") or ""
    text = str(text).replace("\n", " ").strip()
    if len(text) > 220:
        text = text[:220] + "..."
    return f"{node_type}: {text}" if text else node_type


def build_prompt_context_for_clause(paragraph_uid: str, hops: int = 1) -> dict:
    seed = _fetch_seed_clause(paragraph_uid)
    if not seed:
        return {
            "paragraph_uid": paragraph_uid,
            "is_isolated": True,
            "nodes": [],
            "relations": [],
            "prompt_context": "[SEED]\nnot_found"
        }

    rows = _fetch_hop_edges(paragraph_uid, hops=hops)
    node_map = {}
    rel_set = set()

    # include seed node in node_map
    node_map[seed["clause_node_id"]] = {
        "node_id": seed["clause_node_id"],
        "node_type": "Clause",
        "label": seed.get("source_paragraph_id") or seed["clause_node_id"],
        "props": {
            "text": seed.get("clause_text", ""),
            "paragraph_uid": seed.get("paragraph_uid"),
            "source_paragraph_id": seed.get("source_paragraph_id"),
        },
    }

    for r in rows:
        s_id = r["source_id"]
        t_id = r["target_id"]

        node_map[s_id] = {
            "node_id": s_id,
            "node_type": r.get("source_type", "KGNode"),
            "label": r.get("source_label", ""),
            "props": r.get("source_props") or {},
        }
        node_map[t_id] = {
            "node_id": t_id,
            "node_type": r.get("target_type", "KGNode"),
            "label": r.get("target_label", ""),
            "props": r.get("target_props") or {},
        }

        rel_key = (s_id, r["rel_type"], t_id)
        rel_set.add(rel_key)

    nodes = list(node_map.values())
    relations = [{"source_id": s, "rel_type": rt, "target_id": t} for (s, rt, t) in sorted(rel_set)]
    is_isolated = len(relations) == 0

    # prompt-friendly text
    lines = []
    lines.append("[SEED]")
    lines.append(f"contract: {seed['contract']}")
    lines.append(f"clause_node_id: {seed['clause_node_id']}")
    lines.append(f"source_paragraph_id: {seed.get('source_paragraph_id')}")
    lines.append(f"paragraph_uid: {seed.get('paragraph_uid')}")
    lines.append(f"seed_text: {str(seed.get('clause_text','')).replace(chr(10), ' ').strip()[:500]}")
    lines.append("")

    lines.append(f"[NODES_{hops}HOP]")
    for n in sorted(nodes, key=lambda x: (x.get("node_type", ""), x.get("node_id", ""))):
        snippet = _node_snippet(n.get("node_type", "KGNode"), n.get("props") or {})
        lines.append(f"- {n['node_id']} | {n.get('node_type')} | {snippet}")
    lines.append("")

    lines.append(f"[RELATIONS_{hops}HOP]")
    for rel in relations:
        lines.append(f"- {rel['source_id']} -[{rel['rel_type']}]-> {rel['target_id']}")

    return {
        "paragraph_uid": paragraph_uid,
        "contract": seed["contract"],
        "clause_node_id": seed["clause_node_id"],
        "source_paragraph_id": seed.get("source_paragraph_id"),
        "is_isolated": is_isolated,
        "nodes": nodes,
        "relations": relations,
        "prompt_context": "\n".join(lines),
    }


def build_1hop_prompt_contexts(document_list: list[str], top_k: int = 5) -> list[dict]:
    topk_df = select_top_k_non_isolated(document_list=document_list, top_k=top_k)
    out = []
    for row in topk_df.to_dict("records"):
        out.append(build_prompt_context_for_clause(row["paragraph_uid"], hops=1))
    return out


def build_2hop_prompt_contexts(document_list: list[str], top_k: int = 5) -> list[dict]:
    topk_df = select_top_k_non_isolated(document_list=document_list, top_k=top_k)
    out = []
    for row in topk_df.to_dict("records"):
        out.append(build_prompt_context_for_clause(row["paragraph_uid"], hops=2))
    return out


# Example usage:
topk_df = select_top_k_non_isolated(document_list, top_k=5)
display(topk_df[["contract", "source_paragraph_id", "paragraph_uid", "base_relationsCount", "kg_degree"]])
one_hop_payloads = build_1hop_prompt_contexts(document_list, top_k=5)
two_hop_payloads = build_2hop_prompt_contexts(document_list, top_k=5)
print(two_hop_payloads[0]["prompt_context"])

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=49, offset=170>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 170, 'line': 4, 'column': 49}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (ct:Contract)-[:CONTAINS]->(c:Clause)\n    OPTIONAL MATCH (ct)-[:CONTAINS]->(c)-[r]-(:KGNode)<-[:CONTAINS]-(ct)\n    WITH ct.path AS contract, c, count(DISTINCT id(r)) AS kg_degree\n    WHERE kg_degree > 0\n      AND ANY(doc IN $document_list WHERE contract CONTAINS doc)\n    RETURN\n      contract,\n      c.node_id AS clause_node_id,\n      c.source_paragraph_id AS source_paragraph_id,\n      c.paragraph_uid AS paragraph_uid,\n      kg_degree\n    '

,contract,source_paragraph_id,paragraph_uid,base_relationsCount,kg_degree
0,/home/luis/Documents/FGV/Laboratory/document-g...,"BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1...",6d843a956f1adcbf7394d27457e8342f020a9ed8,121,121
1,/home/luis/Documents/FGV/Laboratory/document-g...,"BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1...",c3dcf35efbbd129ee4e08d34cb26109be2dc9737,36,31
2,/home/luis/Documents/FGV/Laboratory/document-g...,"BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1...",102fafa0ede1ad48835bc9d844bf234a120a5986,35,31
3,/home/luis/Documents/FGV/Laboratory/document-g...,"BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1...",27aa2a37e94374ded441a3fc6491ab467ffa30d1,34,31
4,/home/luis/Documents/FGV/Laboratory/document-g...,"BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1...",c0ca305f958217b50991bc9690c0c2e5abb4a281,27,27
5,/home/luis/Documents/FGV/Laboratory/document-g...,BLUEFLYINC_03_27_2002-EX-10.27-e-business Host...,5b869cb5dd4181e2d1fa9369658bade12df646aa,23,23
6,/home/luis/Documents/FGV/Laboratory/document-g...,BLUEFLYINC_03_27_2002-EX-10.27-e-business Host...,73d6b2e02e341ef55b895737ad0340470d984fb0,8,8
7,/home/luis/Documents/FGV/Laboratory/document-g...,BLUEFLYINC_03_27_2002-EX-10.27-e-business Host...,c222917d975e61e910f6bd65ca4d075e445d9692,8,8
8,/home/luis/Documents/FGV/Laboratory/document-g...,BLUEFLYINC_03_27_2002-EX-10.27-e-business Host...,e0633e8c9bba5eb0a6944c50bb5eb38b71b7b184,6,6
9,/home/luis/Documents/FGV/Laboratory/document-g...,BLUEFLYINC_03_27_2002-EX-10.27-e-business Host...,e66ef6eee17776881f3fa30b0de56fd46c847b2b,6,5
10,/home/luis/Documents/FGV/Laboratory/document-g...,HealthcentralCom_19991108_S-1A_EX-10.27_662329...,151d55f9ea0045b49cca9fc0f0e4a0be45e35ad2,2,4
11,/home/luis/Documents/FGV/Laboratory/document-g...,HealthcentralCom_19991108_S-1A_EX-10.27_662329...,1bd9d869d7aee8927bac521eed027ba74c2424dc,1,2
12,/home/luis/Documents/FGV/Laboratory/document-g...,HealthcentralCom_19991108_S-1A_EX-10.27_662329...,728175baca99a419d9f87ca75760f8e7cf144856,1,2
13,/home/luis/Documents/FGV/Laboratory/document-g...,HealthcentralCom_19991108_S-1A_EX-10.27_662329...,e68bc9c1c2ebb65f2dee54c03093d6a0ddaec730,1,2
14,/home/luis/Documents/FGV/Laboratory/document-g...,HealthcentralCom_19991108_S-1A_EX-10.27_662329...,43004e17d4ee7c6073f0b7a4472b404e50d82278,1,2
15,/home/luis/Documents/FGV/Laboratory/document-g...,LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_...,0a3ca0c7211beb712106f2eb83b4e41507ff9c8f,38,38
16,/home/luis/Documents/FGV/Laboratory/document-g...,LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_...,45736548f7e35504b24a48ad8481cd10d885e32f,13,15
17,/home/luis/Documents/FGV/Laboratory/document-g...,LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_...,6fbb673ff89b902981940c32cee1436b71c894b8,13,13
18,/home/luis/Documents/FGV/Laboratory/document-g...,LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_...,f9047369067aecb510cddc383d51d4435169f8ec,5,5
19,/home/luis/Documents/FGV/Laboratory/document-g...,LinkPlusCorp_20050802_8-K_EX-10_3240252_EX-10_...,c34875a8f5856d01b3b1f9e3a93f0cfdb57d8e04,5,3

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=49, offset=170>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 170, 'line': 4, 'column': 49}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (ct:Contract)-[:CONTAINS]->(c:Clause)\n    OPTIONAL MATCH (ct)-[:CONTAINS]->(c)-[r]-(:KGNode)<-[:CONTAINS]-(ct)\n    WITH ct.path AS contract, c, count(DISTINCT id(r)) AS kg_degree\n    WHERE kg_degree > 0\n      AND ANY(doc IN $document_list WHERE contract CONTAINS doc)\n    RETURN\n      contract,\n      c.node_id AS clause_node_id,\n      c.source_paragraph_id AS source_paragraph_id,\n      c.paragraph_uid AS paragraph_uid,\n      kg_degree\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=49, offset=170>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 170, 'line': 4, 'column': 49}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (ct:Contract)-[:CONTAINS]->(c:Clause)\n    OPTIONAL MATCH (ct)-[:CONTAINS]->(c)-[r]-(:KGNode)<-[:CONTAINS]-(ct)\n    WITH ct.path AS contract, c, count(DISTINCT id(r)) AS kg_degree\n    WHERE kg_degree > 0\n      AND ANY(doc IN $document_list WHERE contract CONTAINS doc)\n    RETURN\n      contract,\n      c.node_id AS clause_node_id,\n      c.source_paragraph_id AS source_paragraph_id,\n      c.paragraph_uid AS paragraph_uid,\n      kg_degree\n    '

[SEED]
contract: /home/luis/Documents/FGV/Laboratory/document-graph/infra/json/graph/BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1-Supply Agreement.json
clause_node_id: 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-545
source_paragraph_id: BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1-Supply Agreement-p-545
paragraph_uid: 6d843a956f1adcbf7394d27457e8342f020a9ed8
seed_text: 15.7 Survival. Other than obligations which have accrued and are outstanding as of the date of any expiration or termination of this Agreement, and except as otherwise expressly provided in this Agreement or the Quality Agreement or as otherwise mutually agreed by the Parties in writing, all rights granted and obligations undertaken by the Parties hereunder shall terminate immediately upon the termination or expiration of this Agreement, subject to Section 15.4 above and except for the following

[NODES_2HOP]
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-138 | Clause | Clause: ARTICLE 2 SUPPLY OF PRODUCT; ALLIANCE MANAGERS; JOINT STEERING COMMITTEE
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-149 | Clause | Clause: 2.2 Permitted Use; Restrictions on Use.
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-151 | Clause | Clause: (a) The supply of the Miltenyi Products hereunder conveys to Bellicum the limited, non-exclusive, non-transferable (except as expressly provided herein, including as set forth in Article 17) right to use, and to permit i...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-152 | Clause | Clause: (b) Bellicum shall not use, and shall cause its Subcontractors and Licensees not to use the Miltenyi Products and/or any component thereof for any purpose or in any manner whatsoever other than a Permitted Use expressly ...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-153 | Clause | Clause: (c) Including for purposes of Section 8.2, Bellicum shall promptly notify Miltenyi in writing of any additional Bellicum Product from time to time manufactured by or on behalf of Bellicum (or any of its Licensees, if any...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-154 | Clause | Clause: (d) Except as expressly provided in this Agreement, no other right, express or implied, is conveyed by the sale or purchase of the Miltenyi Products (including the right to make or have made Miltenyi Products). Except as...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-155 | Clause | Clause: (e) Bellicum may offer and permit its Licensees and Subcontractors (if any) to use the Miltenyi Products supplied hereunder only if and so long as such use is in compliance with the terms and conditions of this Agreement...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-156 | Clause | Clause: (f) Bellicum acknowledges that the Miltenyi Products should be used with the same caution applied to any potentially hazardous compound. Use of the Miltenyi Products by Bellicum, its Licensees or Subcontractors shall be ...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-157 | Clause | Clause: (g) Without limitation to the generality of clauses (a) through (e) above, Bellicum further will not, and will cause its Licensees and Subcontractors not to, without express prior written consent from Miltenyi:
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-158 | Clause | Clause: (1) Modify or alter, or cause any Third Party to modify or alter, any Miltenyi Product supplied hereunder other than in connection with its Permitted Use;
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-162 | Clause | Clause: (2) Reverse engineer, disassemble or otherwise analyze, or cause any Third Party to reverse engineer, disassemble or otherwise analyze, any Miltenyi Product supplied hereunder, in whole or in part; provided, however, tha...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-163 | Clause | Clause: (3) Transfer any Miltenyi Product supplied hereunder to any Third Party, except to Bellicum Subcontractors or Licensees solely for the Permitted Use or for training or validation purposes in connection with Bellicum’s de...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-164 | Clause | Clause: (4) Resell Miltenyi Product supplied hereunder to any Third Party, including Bellicum Subcontractors and Licensees, without prior express written permission from Miltenyi; or
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-165 | Clause | Clause: (5) Transfer, use, import or export any Miltenyi Product supplied to Bellicum hereunder in any country or territory other than the Designated Countries.
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-166 | Clause | Clause: 2.3 Additional Countries. Miltenyi acknowledges that Bellicum and/or its Licensees may from time to time desire to use Miltenyi Products in one or more countries that are currently not part of the Designated Countries (e...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-178 | Clause | Clause: 2.7 Violations. Nothing herein contained shall oblige Miltenyi to continue supplying, or Bellicum to continue ordering or purchasing, any Miltenyi Product if such supply or purchase is reasonably believed by Miltenyi or ...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-187 | Clause | Clause: (b) To the extent that the rights granted to Bellicum hereunder (including Bellicum’s right to use each Miltenyi Product for its Permitted Use) are shared with one or more of its Subcontractors or Licensees in accordance...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-30 | Clause | Clause: “Agreement” means this Supply Agreement, including Exhibits A, B, C, D, E, F and G attached hereto and incorporated herein, as amended from time to time in accordance with Section 20.3 hereof.
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-381 | Clause | Clause: ARTICLE 7 ACCEPTANCE AND REJECTION.
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-382 | Clause | Clause: 7.1 Acceptance Testing. Bellicum or (for Miltenyi Product purchased by Bellicum but shipped directly to a Bellicum’s Affiliate,
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-383 | Clause | Clause: Subcontractor, or Licensee) Bellicum’s designated recipient of the
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-385 | Clause | Clause: shipment of Miltenyi Product will promptly upon Delivery visually inspect each shipment of Miltenyi Product delivered hereunder to (i) determine whether such Miltenyi Product is damaged and (ii) verify that the quantity ...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-389 | Clause | Clause: perform, or have its Affiliate, Subcontractor, or Licensee (as the case may be) perform, incoming quality assurance testing on each shipment of Miltenyi Product in accordance with the Bellicum-approved quality control te...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-390 | Clause | Clause: 7.2 Rejection. Bellicum or its designee shall have the right to reject any shipment of Miltenyi Products that does not conform with the applicable Miltenyi Product Warranty at the time of Delivery when tested in accordan...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-391 | Clause | Clause: 7.3 Latent Defects. Bellicum shall have the further right to reject such quantities of Miltenyi Product accepted or deemed accepted pursuant to Section 7.2 above by providing a Rejection Notice on the grounds that all or...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-392 | Clause | Clause: 7.4 Confirmation. After its receipt of a Rejection Notice from Bellicum or its designee pursuant to Section 7.2, Miltenyi shall notify Bellicum in writing as soon as reasonably practical whether or not it accepts Bellicu...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-393 | Clause | Clause: 7.5 Return or Destruction of Rejected Products. Bellicum may not return or destroy any batch of Miltenyi Products until it receives written notification from Miltenyi that Miltenyi does not dispute that such batch fails ...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-397 | Clause | Clause: such destruction. Upon receipt of Miltenyi’s request for return, Bellicum shall promptly return the rejected batch of Miltenyi Products to Miltenyi. In each case, Miltenyi will reimburse Bellicum for the documented, reas...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-398 | Clause | Clause: 7.6 Replacement or Refund. Bellicum shall not be required to pay any invoice with respect to any shipment of Miltenyi Products properly rejected pursuant to this Section 7.2. Notwithstanding the foregoing, Bellicum shall...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-399 | Clause | Clause: 7.7 Exceptions. Bellicum’s rights of rejection, return, refund and replacement set forth in this Article 7 shall not apply to any Miltenyi Product that is non-conforming due to damage (i) caused by Bellicum, its Affiliat...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-400 | Clause | Clause: (ii) that occurs after Delivery of such Miltenyi Product in accordance with this Agreement, including any damage caused thereafter by accident, fire or other hazard, and Miltenyi shall have no liability or responsibility...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-403 | Clause | Clause: 8.2 Milestone Payments. For each particular Bellicum Product, Bellicum will pay to Miltenyi [...***...], one-time only milestone payments of [...***...] Euro (€[...***...]) each, [...***...] milestone payment correspondi...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-437 | Clause | Clause: ARTICLE 10 INTELLECTUAL PROPERTY
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-438 | Clause | Clause: 10.1 Existing Intellectual Property. Except as the Parties may otherwise expressly agree in writing, each Party shall continue to own all rights, including all Intellectual Property Rights, in and title to its Technology...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-447 | Clause | Clause: controls and shall continue to own and control all rights (including all Intellectual Property Rights) in the Bellicum Technology and Bellicum Products (and any Intellectual Property rights thereof), and Miltenyi shall n...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-448 | Clause | Clause: 10.2 Limited License. Miltenyi hereby grants to Bellicum, subject to all the terms and conditions of this Agreement, a limited non-exclusive right and license under the Miltenyi Technology incorporated or embodied in the...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-449 | Clause | Clause: 10.3 Notification. Miltenyi will promptly notify Bellicum in writing of Miltenyi’s receipt of any written claim or demand from any Third Party alleging that the practice of Miltenyi Technology infringes such Third Party’...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-450 | Clause | Clause: 10.4 Disclaimer. Except as otherwise expressly provided herein, nothing contained in this Agreement shall be construed or interpreted, either expressly or by implication, estoppel or otherwise, as: (i) a grant, transfer ...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-451 | Clause | Clause: ARTICLE 11 WARRANTIES
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-452 | Clause | Clause: 11.1 Miltenyi Product Warranty. Subject to Section 11.4 below, Miltenyi warrants and represents and covenants to Bellicum that Miltenyi Product Delivered hereunder will:
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-453 | Clause | Clause: (1) be manufactured, tested and Devilvered by Miltenyi in accordance with all applicable marketing approvals (if any), Agreed Standards, the terms of this Agreement and other Applicable Laws applicable at the place of ma...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-454 | Clause | Clause: (2) conform to Product Specifications at the time of Delivery;
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-455 | Clause | Clause: (3) meet quality and purity characteristics that Miltenyi purports or represents that such Miltenyi Product possesses through its assigned expiry date (shelf life);
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-456 | Clause | Clause: (4) be supplied under a quality system in accordance and compliance with the Quality Agreement,
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-457 | Clause | Clause: (5) not be adulterated or mislabeled under Applicable Laws, and
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-458 | Clause | Clause: (6) at the time of Delivery, be delivered with full title and be free and clear of any lien or encumbrance
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-464 | Clause | Clause: (collectively, the “Miltenyi Product Warranty”). Bellicum’s remedies and Miltenyi liability with respect to this Miltenyi Product Warranty are set forth in Section 7.6 and as otherwise expressly set forth in this Agreeme...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-466 | Clause | Clause: 11.2 Additional Miltenyi Representations, Warranties, and Covenants. Miltenyi further represents and warrants and covenants to Bellicum that:
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-467 | Clause | Clause: (1) Miltenyi and its Affiliates and Subcontractors have the scientific, technical and other requisite competencies, and full right and power to perform the obligations set forth in this Agreement, and Miltenyi covenants ...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-468 | Clause | Clause: (2) To Miltenyi’s knowledge and after due inquiry, on the Effective Date, Miltenyi owns all right, title, and interest in and to, or otherwise possesses all necessary rights and licenses under, the Miltenyi Technology an...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-469 | Clause | Clause: (3) As of the Effective Date, Miltenyi has not received any written communication from any Third Party alleging that the manufacture, use, sale, offer for sale or import of any Miltenyi Product infringes any Third Party ...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-470 | Clause | Clause: (4) To Miltenyi’s knowledge on the Effective Date, except with respect to the agreements listed on Exhibit D hereto there are no agreements between Miltenyi and a Third Party that would impose any payment obligation on B...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-471 | Clause | Clause: 11.3 Bellicum Representations, Warranties, and Covenants. Bellicum represents, warrants and covenants to Miltenyi that:
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-472 | Clause | Clause: (1) Bellicum has the scientific, technical and other requisite competencies to determine the suitability of each Miltenyi Product purchased hereunder for the use to which Bellicum will put such Miltenyi Product;
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-473 | Clause | Clause: (2) As of the Effective Date, the Product Specifications are adequate to confirm the suitability of the Miltenyi Product (including its packaging and labelling) for the uses to which such Miltenyi Product will be put by ...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-474 | Clause | Clause: (3) Bellicum will perform, and will cause its Subcontractors and Licensees to perform, sufficient incoming inspection of each supplied Miltenyi Product to comply with its obligations under this Agreement and under all Ap...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-475 | Clause | Clause: (4) Bellicum shall manufacture (and require and ensure that any Subcontractor or Licensee will manufacture) Bellicum Products using appropriate standards of care and quality in accordance with Applicable Laws and all req...
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-476 | Clause | Clause: (5) Bellicum shall use, and will cause its Subcontractors and Licensees to use, Miltenyi Products in accordance with all Applicable Laws and all requirements of Regulatory Authorities applicable to such use.
- 4a2187cb60da96c331433608de54893734fbde45:Clause:BELLICUMPHARMACEUTICALS_INC_05_07_2019-EX-10.1-Supply_Agreement-p-480 | Clause | Clause: 11.4 Disclaimer.